### ISSUE TITLE
Add contextual menus to Configurations Maps

### ISSUE THREAD

**Issue by eMaringolo** [instantiations/tonel-vast#38]
Currently we only provide contextual menus to load applications from the Application Manager, we should also add the option to Configurations Maps browsers (for config maps) and the Visual Organizer (for apps).

**Comment by simonfranz** [comment]
Last time I've checked selecting multiple applications and then click to export to Tonel the selected applications we're ignored. I had to reselect all selected applications.is this already adressed?

**Comment by eMaringolo** [comment]
@simonfranz this was solved in 0a8594a. 

There are also a few extra things in the interactive dialogs. In the future we might have a dialog of its own to avoid all these prompts while exporting.

Since there is no provided menu hook to the VA Organizer, we dropped that for a future release.
