### ISSUE TITLE
Write out own format version when exporting

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#50]
For Instantiations, backward compatibility with customers is important. Therefore, we should store  (maybe as part of the `/source/.properties`) a `vaFormatVersion: "1.1"` kind of attribute were we write down out VAST format version in which that project was written. This would allow us write migration tools or things like that if the format changes over time.

**Comment by eMaringolo** [comment]
This was solved by adding the `#formatVersion` attribute to the `source/.properties` STON content.
