### ISSUE TITLE
Some extension methods are not being imported

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#53]
Hi Esteban, 
I am trying to import the example from [here](https://github.com/Noschvie/Nextcloud-Login-Flow-vast) of @Noschvie with the following lines:

```smalltalk
| loader path |
path := (CfsPath named: 'z:\Common\Development\git\Nextcloud-Login-Flow-vast\VASmalltalk\').
loader := TonelLoader readFromPath: path.
loader
	beUnattended.
loader loadAllApplications. 
```

The `loadAllApplications` finishes OK but there are some extensions on `Object` that were not loaded. These are defined in `NdevLoggingFramework` subapp and you can see they were correctly written [here](https://github.com/Noschvie/Nextcloud-Login-Flow-vast/blob/master/VASmalltalk/source/NdevLoggingFramework/Object.extension.st).

I noticed some compilation errors on the Transcript but none of them seem related to this one in particular that I am reporting. 

Any idea? 

Thanks in advance,

**Comment by eMaringolo** [comment]
I can confirm this, it is a bug in the detection of changes between the base edition and the what is being loaded from Tonel.

There is a workaround until I fix this, that is to [set the loader to always create editions](https://github.com/instantiations/tonel-vast/blob/master/docs/strategies.md#common-options).
