### ISSUE TITLE
AbtShelProgramStarterUnixPlatformSubApp missing

### ISSUE THREAD

**Issue by HeSe** [instantiations/tonel-vast#54]
Tonel can currently not be loaded into a Unix environment because a AbtShellProgramStarter specific to Unix  is missing. (an implementation of AbtShelProgramStarterUnixPlatformSubApp is missing).
For Windows there is a AbtShelProgramStarterWindowsPlatformSubApp available.

**Comment by marianopeck** [comment]
Maybe a duplicate of #60 ?
