### ISSUE TITLE
TonelLoaderTest fails due to missing directory: ".\TonelLoaderTest"

### ISSUE THREAD

**Issue by floxeipi** [instantiations/tonel-vast#59]
I followed the instructions on "https://github.com/instantiations/tonel-vast#installation" for VAST 9.2.2 and performed the provided Unit-Tests. There all three test cases of TonelLoaderTest are failing due to the missing directory ".\TonelLoaderTest". Simply creating an empty directory does not help.

**Comment by eMaringolo** [comment]
Hi, thanks for reporting,, this is an issue with the packaging of the tests, the apps are distributed in the `ToneLoaderTestsApp.dat`, but we need to set up the directory first. I'll correct this.

**Comment by eMaringolo** [comment]
We will update the documentation in how to run the tests as well as the `setUp` method in the Test class to have the suite properly initialized.

**Comment by eMaringolo** [comment]
In the latest commit (bf5c2ada1), `TonelLoaderTest` has a class side `testRepositoriesPath: aCfsPath` method that defines the base 
directory where the sample repositories are located.

You should assign to it the path where the `tonel-vast` repository was cloned plus the `tests` subdirectory.

E.g.
```smalltalk
TonelLoaderTest testRepositoriesPath: 
  ((CfsPath named: CfsDirectoryDescriptor getcwd) append: '..\tonel-repos\tonel-vast\tests')
```
