### ISSUE TITLE
Add support for configuration maps 

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#6]
Right now we only support apps as the Tonel unit to write and read but on the future, we would also need to be able to do this at Configuration Map level. For this, we have discussed a lot with Dale Henrichs and see if we can use the same idea of Rowan about "configs".

**Comment by dalehenrich** [comment]
This issue corresponds with GemTalk/Rowan#553.

**Comment by eMaringolo** [comment]
This was already solved in another commit, and released in the milestone 1.1
