### ISSUE TITLE
Tonel still depends on Sts

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#67]
`TonelLoaderApplication >> createEdition` uses the method `do:forApp:withSuperUser:` which is from Sts. 

There may be more.

**Comment by marianopeck** [comment]
OK. I have just run Smalllint, with just the rule "Message sent but not implemented in application" to all Tonel packages and I can see all the methods needed to be fixed. See attached. 

![Screen Shot 2020-12-22 at 4 45 33 PM](https://user-images.githubusercontent.com/1032834/102927265-66b60780-4475-11eb-829c-96214782db48.png)

![Screen Shot 2020-12-22 at 4 46 30 PM](https://user-images.githubusercontent.com/1032834/102927285-6ddd1580-4475-11eb-928c-7ded95043687.png)

**Comment by eMaringolo** [comment]
Solved with 2bcb85c
