### ISSUE TITLE
Allow specifying a list of packages to be ignored

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#82]
Right now all of the packages of the repo are evaluated for the compute of the prerequisites. We should allow a way to ignore a list...for example, if we are loading in VAST, we want to avoid processing the packages for GemStone or Pharo. 
Ideas:

* Hardcoded list instead the loader
* `loader ignorePackages: #( 'squeak' , 'pharo' ..  )`
* `loader ignorePackagesSuchThat: [:aPackageName :  #('squeak' ) includes: aPacakgeName  ]`

**Comment by eMaringolo** [comment]
I added a `prerequisitesFilter` attribute to `TonelLoader` in 203e4b8, it should be a one-argument block that will receiver a `TonelApplication` as argument.

```smalltalk
loader prerequisitesFilter: [:tonelApp | 
	#('pharo' 'gemstone' 'squeak') noneSatisfy: [:pattern |
		('*', pattern, '*') match: tonelApp packageName ]
	].
```
