### ISSUE TITLE
New loader strategy for computing prereqs

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#86]
Right now, the prereqs are always tried to be guessed by the loader. Sometimes, this "guess" is correct but we still need to disable or provide our custom mapping to prereqs...see for example: https://github.com/SeasideSt/Seaside/issues/1251

Therefore, we propose having a prereq compute strategy that could be specified to the loader:

* Null strategy..computes nothing assumes no prereq
* Automatic compute (what it does now)
* User-specified table that maps dependencies between packages

**Comment by eMaringolo** [comment]
This was successfully implemented [and documented](https://github.com/instantiations/tonel-vast/blob/master/docs/strategies.md#tonelloaderpackagetableprereqsstrategy) in a previous commit.

The null prereqs strategy could be achieved by specifying an empty table.
