### ISSUE TITLE
Tonel is duplicating protocols

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#90]
When I import from Seaside, the imported class all have duplicated "protocols". Each protocol appears twice and all the methods are always in one of them and the other is empty. See attached screenshot as an example
<img width="928" alt="Screen Shot 2021-07-02 at 10 21 44 AM" src="https://user-images.githubusercontent.com/1032834/124280707-6468f000-db1f-11eb-9951-2d2ad9326184.png">

**Comment by eMaringolo** [comment]
Why isn't configuration duplicated?
Were you starting from a blank image/library or it created the methods on top of a base edition?

**Comment by eMaringolo** [comment]
This was caused by a mismatch of Symbol and String used for categories, now all categories parsed from the file are converted to String when read.
