### ISSUE TITLE
Tonel loading installs a bad debugger class

### ISSUE THREAD

**Issue by marianopeck** [instantiations/tonel-vast#95]
To restore back the good debugger you have to evaluate: `EsImageStartUp debuggerClass: StsDebugger.`

I don't know why the debugger class is changed when loading Tonel....

**Comment by eMaringolo** [comment]
The reason was that one of the application depends on EtTools, which in turn depends on EtBaseTools, which has a `loaded` method, that sets `DbgDebugger` as the default debugger.
